# Estructuras de Control

Las estructuras de control son el esqueleto del lenguage de la programación. Entre las estructuras de control encontramos los bucles, las sentencias condicionales. En este clase vamos a ver las estructuras de control básicas de la programación en R. 

PARTE 1:
- if-else
- for
- while
- repeat/break

PARTE 2:
- apply/sapply/lapply/tapply
- programación paralelizada

## If-else


En esta sección vamos a ver como implementar una condición en R. Las condiciones se expresan de la siguiente manera:

- a == b   (es TRUE si a y b son IGUALES) 
- a != b   (es TRUE si a y b son DISTINTO)
- a >= b   (es TRUE si a es MAYOR o IGUAL a b)
- a <= b   (es TRUE si a es MENOR o IGUAL a b)
- a < b || a == c (es TRUE si a es MENOR que b o si a es IGUAL a c)
- a <= b && a == c (es TRUE si a es MENOR que b y si a es IGUAL a c)

Si se ejecuta la condición se obtiene un objeto de tipo booleano (TRUE o FALSE), que indica si se cumple o no dicha condición. Los elementos a y b pueden ser en principio cualquier objeto: lista, número, caracter ... 

In [1]:
a <- 2
b <- 5
c <- 2

a == 2
a == b
a == c
a != 2
b >= c

a == c && a == b
a == c || a == b

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

La condición también puede estar asignada a un objeto, como por ejemplo:

In [2]:
cond1 <- a == 2

# Aqui está asignada la condicion a cond1
if (cond1) {
    print("Se cumple la condicion")
} else {
    print("No se cumple la condicion")
}
paste("Esto se debe a que el objeto cond1 es de la clase:",class(cond1))

# ... que equivale a esto
if (a == 2) {
    print("Se cumple la condicion")
} else {
    print("No se cumple la condicion")
}

[1] "Se cumple la condicion"


[1] "Esto se debe a que el objeto cond1 es de la clase: logical"

[1] "Se cumple la condicion"


Si ponemos el símbolo ! antes de la condición indica DISTINTO a la condición:

In [4]:
paste("Por tanto si cond1 es",cond1,"entonces !cond1 es",!cond1)

if (!cond1) {
    print("Se cumple la condicion")
} else {
    print("No se cumple la condicion")
}

[1] "Por tanto si cond1 es TRUE entonces !cond1 es FALSE"

[1] "No se cumple la condicion"


Hay funciones importantes de R que nos permiten obtener información sobre sobre los objetos, de tal manera que dichas funciones nos "contestan" con True o False .
Por ejemplo, a la pregunta: ¿Hay algún NaN en esta matriz? se encarga de responderla la función any.na(), cuya salida de la función es una variable booleana.

In [ ]:
vec <- c(1,5,NA,7)
cond <- anyNA(vec)
if (cond) {
    paste("En este dataset hay NaNs")
} else {
    print("En este dataset no hay NaNs")
}

Otro ejemplo, a la pregunta: ¿Es esto un NaN en esta matriz? se encarga de responderla la función is.na(), cuya salida de la función es una variable booleana.

In [1]:
vec <- c(1,5,NA,7)
is.na(vec)

[1] FALSE FALSE  TRUE FALSE

En este caso anterior, si introdujesemos lo siguiente, salta un warning ya que vec no tiene longitud 1.

In [2]:
vec <- c(1,5,NA,7)
cond <- is.na(vec)
if (cond) {
    num_NA <- which(vec == NA)
    paste("En este dataset hay NaNs, concretamente hay",num_NA)
} else {
    print("En este dataset no hay NaNs")
}

which(vec == NA)

Warning message in if (cond) {:
“the condition has length > 1 and only the first element will be used”

[1] "En este dataset no hay NaNs"


integer(0)

En resumidas cuentas, en la estructura if (condicion), lo importante es que la condicion sea un objeto de tipo booleano y a ser posible cuya longitud sea 1!

Hay dos grandes diferencias con respecto a python: 1) la condición va entre paréntesis mientras que en python no y 2) el cuerpo de la condición va entre llaves sin importar el sangrado de línea mientras que en python es al revés (prima el sangrado de línea y no hay que poner llaves).

In [11]:
## En R
#if (condicion) {
#    # haz algo aqui
#} else {
#    # sino haz algo aqui
#}
#
## En python
#if condicion:
#    #haz algo aqui
#else:
#    #sino haz algo aqui

In [8]:
?which

A continuación se pueden ver un ejemplo completo de la aplicacion del if else:

In [12]:
my_list = list("nombre" = c("Paco","Álvaro","Juan"), 
               "apellido" = c("López","Castillo","Robles")
              ) 
nom <- readline(prompt="Le toca el turno a:")

if (any(my_list$nombre == nom)) {
    indice <- which(my_list$nombre==nom)
    apell <- readline(prompt="Me puede decir su apellido por favor:")
    if (which(my_list$apellido == apell)==indice) {
        paste("Muy bien",nom,apell,"pase a la sala")
    }
    else {
        paste("Lo siento yo estoy buscando a otro",nom)
    }
}else {
    paste("No hay nadie con ese nombre en la sala")
}       

Le toca el turno a:Paco
Me puede decir su apellido por favor:López


[1] "Muy bien Paco López pase a la sala"

En realidad, el ejercicio anterior tiene un pequeño fallo ya que no es capaz de asociar los apellidos con los nombres. Es decir, cuando introduces el apellido el código tan solo busca si ese apellido está en my_list, independientemente de si efectivamente el apellido en cuestión está asociado a algún nombre en particular (Si introduces de nombre "Paco" y de apellido "Castillo" el algoritmo va a llamar a Paco Castillo cuando no hay ningún Paco Castillo). 

EJERCICIO PROPUESTO: asocia los nombres a los apellidos en la siguiente celda (ayuda: utiliza la función which):

EJERCICIO PROPUESTO: En la siguiente celda tienes un vector de datos. Tienes que hacer lo siguiente:
- Identifica los valores menores que 1 y asignales el valor 0.
- Identifica los valores mayores que 0 y multiplicalos por 2.

In [19]:
set.seed(2)
vec <- sample(-100:100,size = 100)
vec

[1] -63  40  14 -67  85  84 -75  61 -10   5  91 -55  43  97 -25  58  80 -59
 [19] -19 -87  19 -31  49 -74 -39 -14  77 -38  66 -78 -99 -73  36  45 -15   4
 [37]  39 -54   8 -76  96 -53 -82  94  48  23  51 -47 -24  55  70 -98   1  37
 [55] -60  18  13  42 -13   0  62  24  75 -65  17 -41 -48  76 -71 -92 -64  46
 [73] -95 -77  27  -5  30   7 -51  79 -58 -20  78  59  26  -1  11  64 -18 -62
 [91]  99 -57  83 -40  22 -80 -56 -91 -89  65

In [24]:
# Solución
if (any(vec<1) && any(vec>0)) {
    ind_mayor_0 <- which(vec>0)
    ind_menor_1 <- which(vec<1)
    vec[ind_menor_1] <- 0
    vec[ind_mayor_0] <- vec[ind_mayor_0]*2
}
vec

[1]   0  80  28   0 170 168   0 122   0  10 182   0  86 194   0 116 160   0
 [19]   0   0  38   0  98   0   0   0 154   0 132   0   0   0  72  90   0   8
 [37]  78   0  16   0 192   0   0 188  96  46 102   0   0 110 140   0   2  74
 [55]   0  36  26  84   0   0 124  48 150   0  34   0   0 152   0   0   0  92
 [73]   0   0  54   0  60  14   0 158   0   0 156 118  52   0  22 128   0   0
 [91] 198   0 166   0  44   0   0   0   0 130

## for

El bucle for permite realizar iteraciones. Una iteración es un ciclo de operaciones que se repiten a través de uno o varios índices Al igual que la condición if, las diferencias con python residen en la presencia de llaves en sustitución de los sangrados de línea. De tal manera que la sintaxis es:
- for (i in vec){cuerpo del bucle}

Si el cuerpo del bucle solo continene una línea se puede poner a continuación y sin llaves:
- for (i in vec) cuerpo del bucle

Podemos iterar sobre elementos de un vector...

In [25]:
medios.transporte <- c("carro", "camion","metro", "moto")
for (vehiculo in medios.transporte) print(vehiculo)

[1] "carro"
[1] "camion"
[1] "metro"
[1] "moto"


... o iterar sobre elementos de una lista.

In [26]:
medios.transporte <- list("carro", "camion","metro", "moto")
for (vehiculo in medios.transporte) print(vehiculo)

[1] "carro"
[1] "camion"
[1] "metro"
[1] "moto"


Si en cada interación vamos a ir rellenando elementos en un vector/matriz/lista es importante inicializarlas antes:

In [27]:
x <- 1:500
y <- x^2
z <- c()
for (i in 1:500) z[i] <- x[i]*y[i]
head(z)

[1]   1   8  27  64 125 216

... si no se hubiese inicializado el vector z pasaría esto:

In [28]:
x <- 1:500
y <- x^2
for (i in 1:500) zz[i] <- x[i]*y[i]
head(z)

ERROR: Error in zz[i] <- x[i] * y[i]: object 'zz' not found


Por ello una parte importante de los bucles for es la inicialización de los objetos.
- Inicializar un vector: c()
- Inicializar una matriz: matrix(data=, ncol=, nrow=)
- Inicializar un array: array(data=,dim=)

Si a los vectores o a las listas se les quiere dar una longitud determinada se puede utilizar la función vector():
- vector(mode="list",length=)
- vector(mode="numeric",length=)

In [30]:
x <- matrix(data = 1:6, ncol = 2, nrow = 3)
y <- x-1
z <- matrix(data = NA, ncol = 2, nrow = 3)
nrow(x)
for (i in 1:nrow(x)) {
  z[i,] <- x[i,]*y[i,]  
} 

print("La matriz x contiene:") 
x
print("La matriz y contiene:") 
y
print("La matriz z contiene:") 
z

[1] 3

[1] "La matriz x contiene:"


[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] "La matriz y contiene:"


[,1] [,2]
[1,] 0    3   
[2,] 1    4   
[3,] 2    5

[1] "La matriz z contiene:"


[,1] [,2]
[1,] 0    12  
[2,] 2    20  
[3,] 6    30

EJERCICIO PROPUESTO: Busca la manera de hacer en tan solo UN bucle for lo que en la siguiente celda está hecho en DOS.

In [37]:
# Con dos bucles for
x <- matrix(data = 1:6, ncol = 2, nrow = 3)
z <- matrix(data = NA, ncol = 3, nrow = 2)
for (i in 1:ncol(x)){
    for (j in 1:nrow(x)){
        z[i,j]= x[j,i]
    }
}
print("La matriz x contiene:") 
x
print("La matriz z (que si os fijais es la traspuesta de x) contiene:") 
z

[1] "La matriz x contiene:"


[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] "La matriz z (que si os fijais es la traspuesta de x) contiene:"


[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [36]:
## Con un bucle for
# Con dos bucles for
x <- matrix(data = 1:6, ncol = 2, nrow = 3)
z <- matrix(data = NA, ncol = 3, nrow = 2)
for (i in 1:ncol(x)){
        z[i,]= x[,i]
}
print("La matriz x contiene:") 
x
print("La matriz z (que si os fijais es la traspuesta de x) contiene:") 
z

[1] "La matriz x contiene:"


[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] "La matriz z (que si os fijais es la traspuesta de x) contiene:"


[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

EJERCICIO PROPUESTO: En la clase de ayer visteis como definir una funcion en R. Utiliza el código del ejercicio anterior (el cual calcula la media a lo largo de la primera dimension para un el array x de 3 dimensiones) para definir una funcion el cual calcule dicha media pero para cualquier array x de 3 dimensiones.

## while, repeat, break

### while

A continuación vamos a ver como utilizar la estructura iterativa while, el cual ejecuta el bucle hasta que se cumple una condicion.

In [30]:
n <- 0
while(n < 10){
    print(paste("Aun voy por el numero",n))
    n <- n+1
}

[1] "Aun voy por el numero 0"
[1] "Aun voy por el numero 1"
[1] "Aun voy por el numero 2"
[1] "Aun voy por el numero 3"
[1] "Aun voy por el numero 4"
[1] "Aun voy por el numero 5"
[1] "Aun voy por el numero 6"
[1] "Aun voy por el numero 7"
[1] "Aun voy por el numero 8"
[1] "Aun voy por el numero 9"


EJERCICIO PROPUESTO: Escriba un algoritmo usando la instrucción while que genere 1000 números al azar con distribución uniforme en [0,1] y los sume hasta llegar a 100. El resultado es el número de sumandos. (Para generar números al azar con dicha distribución utilizar la función runif)

[1] "Se han utilizado 205 números, cuya suma es igual a 100.068509225966"


### repeat, break

Repeat ejecuta el bucle una y otra vez, repitiéndolo hasta que se cumple una condicion donde es necesario que aparezca la secuencia break. De otra manera, el bucle acabaría siendo infinito.

In [31]:
n <-0
suma <- 0
repeat {
    n <- n+1 
    suma <- suma + n
    if ( suma > 1000) break
}
suma
n

[1] 1035

[1] 45

EJERCICIO PROPUESTO: Escriba un algoritmo usando la instrucción repeat que genere 1000 números al azar con distribución uniforme en [0,1] y los sume uno a uno hasta llegar a 100. El resultado es el número de sumandos. (Para generar números al azar con dicha distribución utilizar la función runif)


[1] "Se han utilizado 197 números, cuya suma es igual a 100.242720729439"
